<?xml version="1.0" encoding="utf-8"?><Database Name="Documents" Class="DocumentsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Documents.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DocumentsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accounting" Member="Accountings">
    <Type Name="Accounting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Clipping" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>